project:
  type: book
  output-dir: docs

book:
  title: "数据科学与编程"
  reader-mode: true
  chapters:
    - index.qmd
    
    - part: "R Data Science"
      chapters: 
        - type_class.qmd
        - read_write.qmd
        - useful_function.qmd
        - logical_vector.qmd
        - number_vector.qmd
        # - string_text.qmd
        # - transform_tidy.qmd
        # - functionals.qmd
        # - big_data.qmd
        # - custom_functions.qmd
        - dynamic_report.qmd

    - part: "R → Python"
    #   chapters: 
    #     - R-Python.qmd

    - part: "R Programming"
      chapters: 
        - control_structure.qmd
        - exception_handling.qmd
        - functions.qmd
        - environments.qmd
        - object_oriented_programming.qmd
        - meta_programming.qmd
        - quasiquotation.qmd
        - evaluation.qmd

        
execute:
  cache: true
  message: false 
  warning: false  #阻止消息或警告出现在完成的文件中
  
# eval: false  阻止对代码进行评估。（显然，如果不运行代码，则不会生成任何结果）
# include: false  运行代码，但不会在最终文档中显示代码或结果。
# echo: false  阻止代码，但不会阻止结果出现在完成的文件中
toc: true
toc-depth: 4
number-sections: true
number-depth: 4

code-fold: true
code-tools: true
code-link: true
code-summary: "Show the code"
knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE
    
format: 
  html: 
    theme: cosmo
    df-print: kable
    fig-format: svg
editor: visual



