project:
  type: book
  output-dir: docs

book:
  title: "R 数据科学与编程"
  reader-mode: true
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: "R Data Science"
      chapters: 
        - data_type.qmd
        - data_structure.qmd
        - numeric.qmd
        - logical_operation.qmd
        - string_text.qmd
        
        - base_function.qmd
        - read_write.qmd
        - transform_tidy.qmd
        - functionals.qmd
        - dynamic_report.qmd
        
    - part: "大数据"
      chapters: 
        - big_data.qmd
        - data.table.qmd
        - arrow.qmd
        - polars.qmd
        - Rcpp.qmd
        - R_Python.qmd
    - part: "编程"
      chapters:
      - control_structure.qmd
      - exception_handling.qmd
      - functions.qmd
      - environments.qmd
      - object_oriented_programming.qmd
      - meta_programming.qmd
      - quasiquotation.qmd
      - evaluation.qmd

        
execute:
  cache: true
  message: false 
  warning: false 
# eval: false  阻止对代码进行执行。（显然，如果不运行代码，则不会生成任何结果）
# include: false  运行代码，但不会在最终文档中显示代码或结果。
# echo: false  阻止代码显示，但不会阻止结果出现在完成的文件中
toc: true
toc-depth: 4
number-sections: true
number-depth: 4

code-fold: true
code-tools: true
code-link: true
code-summary: "Show the code"
knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE
    
format: 
  html: 
    theme: cosmo
    df-print: kable
    fig-format: svg
editor: visual



